name: "Release Deploy"

on:
  push:
    branches: [ "main" ]

env:
  VERSION: 7.0.200.${{ github.run_number }}
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check
      uses: actions/checkout@main
      with:
        lfs: "true"
        submodules: "recursive"

    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8.x.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=${{ env.VERSION }}

    - name: Run Tests
      run: dotnet test --no-restore --no-build --configuration Release

    - name: Pack
      run: dotnet pack --no-restore --no-build --configuration Release --include-symbols --include-source -p:Version=${{ env.VERSION }}

    - name: Push to NuGet Feed
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ env.NUGET_API_KEY }}
